/* Trace every motif the site shows from the ORIGINAL artwork.
 *
 * Owner, 9 Sep 2026: "you are not using the same images. I asked you to
 * repurpose existing headers - split them by pieces and animate, not invent
 * new. I like the old style so just use and animate it."
 *
 * So nothing here is drawn by hand. Each include is traced from the raster that
 * was already on the page, by tools/trace-motif.mjs, and the shapes it animates
 * are the artwork's own. Blog posts trace their OWN cover, so every post keeps
 * the picture it already had.
 *
 * usage: node tools/build-motifs.mjs [--posts-only|--pages-only]
 */
import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

const GEN = 'src/img/gen';
const OUT = 'src/_includes/motifs';
const imagery = JSON.parse(fs.readFileSync('src/_data/imagery.json', 'utf8')).slots;
const altOf = (id) => (imagery.find((s) => s.id === id) || {}).alt || '';
const only = process.argv.find((a) => a.startsWith('--'));

// page motifs: [source id, include name]
const PAGES = [
  ['hero-pakalpojumi', 'pakalpojumi'], ['hero-meta-reklama', 'meta'],
  ['hero-seo-pakalpojumi', 'seo'], ['hero-video-reklama', 'video'],
  ['hero-ai-automatizacijas', 'ai'], ['hero-konsultacijas', 'konsultacijas'],
  ['meta-reklamas-motivs', 'kurss-meta'], ['google-ads-motivs', 'kurss-google'],
  ['seo-mekletaja-motivs', 'kurss-seo'], ['tiktok-video-motivs', 'kurss-tiktok'],
  ['kursi-programmas-motivs', 'kurss-hub'],
  ['video-formats-band', 'band-video-formats'], ['meta-targeting-band', 'band-meta-targeting'],
  ['ai-flow-band', 'band-ai-flow'], ['smm-orbit-band', 'band-smm-orbit'],
  ['konsultacijas-saruna', 'band-konsultacijas-saruna'],
  ['smm-cadence-grid', 'band-smm-cadence'], ['services-module-band', 'band-services-module'],
];

const trace = (srcId, name, alt) => {
  const src = path.join(GEN, `${srcId}.webp`);
  if (!fs.existsSync(src)) { console.log(`  MISSING ${srcId}.webp`); return false; }
  try {
    execFileSync('node', ['tools/trace-motif.mjs', src, path.join(OUT, `${name}.njk`)],
      { env: { ...process.env, MOTIF_ALT: alt }, stdio: 'inherit' });
    return true;
  } catch { console.log(`  FAILED ${srcId}`); return false; }
};

let ok = 0;
if (only !== '--posts-only') {
  console.log('page motifs:');
  for (const [srcId, name] of PAGES) if (trace(srcId, name, altOf(srcId))) ok++;
}

if (only !== '--pages-only') {
  console.log('post motifs (each post traces its own cover):');
  const map = {};
  for (const f of fs.readdirSync('src/posts').filter((f) => f.endsWith('.md'))) {
    const head = fs.readFileSync(path.join('src/posts', f), 'utf8').slice(0, 1200);
    const slug = (head.match(/permalink:\s*"\/([^/"]+)\//) || [])[1] || f.replace(/\.md$/, '');
    const img = (head.match(/^image:\s*"\/img\/gen\/([a-z0-9-]+)\.webp"/m) || [])[1];
    const title = (head.match(/^title:\s*"([^"]+)"/m) || [])[1] || '';
    if (!img) { console.log(`  no generated cover: ${slug}`); continue; }
    if (trace(img, `post-${slug}`, `Raksta motīvs: ${title.slice(0, 60)}`)) { map[slug] = `post-${slug}`; ok++; }
  }
  fs.writeFileSync('src/_data/postMotifs.json',
    JSON.stringify({ _comment: 'Generated by tools/build-motifs.mjs — each post traces its own cover.', bySlug: map }, null, 2) + '\n');
  console.log(`  mapped ${Object.keys(map).length} posts`);
}
console.log(`done: ${ok} motifs traced from the original artwork`);
